version: '3.8'
services:
  db:
    image: postgres:13
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks: 
      - db-network
  testdb:
    image: postgres:13
    ports: 
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    networks: 
      - test-db-network

networks:
  db-network:
  test-db-network:

